name: Docker Build and Push

inputs:
  dockerhub_username:
    required: true
    default: ''
  dockerhub_token:
    required: true
    default: ''
  image_name:
    required: true
    default: ''
  docker_file:
    required: true
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Set up QEMU 🐳
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx 🐳
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub 🔑
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}

    - name: Build and push API image 🚀
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ inputs.docker_file }}
        push: true
        tags: goodxyz/${{ inputs.image_name }}:latest
